(()=>{'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),entry=window.MIX_CATALOG.find(g=>g.id===params.get('game'));
function error(message){$('error').hidden=false;$('error-copy').textContent=message;$('new-game').hidden=true;$('legacy').hidden=true;}
if(!entry){error('这个玩法入口不存在，请回目录选择。');return;}
document.title=entry.title+' · Mix';$('game-label').textContent=entry.title;
if(entry.src){const frame=$('legacy'),url=new URL(entry.src,location.href);if(entry.id==='parts'){for(const k of ['level','v'])if(params.has(k))url.searchParams.set(k,params.get(k));}frame.src=url.href;frame.hidden=false;frame.addEventListener('load',()=>{if(entry.id==='parts'&&params.has('level')){params.delete('level');history.replaceState(null,'','play.html?'+params);}});return;}
const script=document.createElement('script');script.src='games/'+entry.id+'.js?v=r4';script.onload=start;script.onerror=()=>error('游戏文件加载失败，刷新或返回目录重试。');document.head.appendChild(script);
function start(){const def=window.MixGames?.[entry.id];if(!def){error('游戏尚未加载，请刷新重试。');return;}
const KEY='mix-clickmove-v1',W=390,H=560,canvas=$('canvas'),ctx=canvas.getContext('2d');let saved={games:{},muted:false};try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw&&typeof raw==='object'&&raw.games&&typeof raw.games==='object'&&!Array.isArray(raw.games))saved=raw;}catch{}
const progress=saved.games[entry.id]||{current:0,completed:[]};progress.completed=Array.isArray(progress.completed)?progress.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<def.levels.length):[];saved.games[entry.id]=progress;
let level=0,game=null,ended=false,won=false,paused=false,last=0,acc=0,frame=0,audioCtx=null,voices=0;const soundEvents=[];const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}};
function unlock(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});}catch{}}
function sound(type,intensity=1,pitch=1){soundEvents.push({type,frame});if(soundEvents.length>100)soundEvents.shift();if(saved.muted||!audioCtx||voices>=12)return;try{const t=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain(),base={pop:650,hit:110,tap:380,collect:730,whoosh:230,win:880,fail:190}[type]||440,d=type==='win'?.35:.1;o.connect(g);g.connect(audioCtx.destination);o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(base*Math.max(.3,Math.min(3,pitch)),t);o.frequency.exponentialRampToValueAtTime(base*.6,t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.055*Math.max(.1,Math.min(1,intensity)),t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.start(t);o.stop(t+d+.01);voices++;o.onended=()=>{voices--;o.disconnect();g.disconnect();};}catch{}}
function updateControls(){$('undo').disabled=!game?.canUndo?.()||won;$('recover').disabled=!game?.canUndo?.();}
function outcome(ok,result={}){if(ended)return;ended=true;won=ok;const message=typeof result==='string'?result:result.reason||result.message; if(ok){if(!progress.completed.includes(level))progress.completed.push(level);progress.current=Math.min(level+1,def.levels.length-1);save();paintLevels();}
$('result-kicker').textContent=ok?'这一关，理顺了':'换个顺序试试';$('result-title').textContent=ok?'过关了！':'卡住了';$('result-copy').textContent=message||(ok?'继续下一关，看看会发生什么。':'悔棋退回一步，保留前面的努力。');$('recover').hidden=ok;$('next').hidden=!ok;$('next').textContent=level+1<def.levels.length?'下一关':'返回试玩目录';$('overlay').hidden=false;updateControls();}
function paintLevels(){$('levels').replaceChildren();def.levels.forEach((l,i)=>{const b=document.createElement('button');b.textContent=i+1;b.className=(i===level?'active ':'')+(progress.completed.includes(i)?'done':'');b.setAttribute('aria-label','第'+(i+1)+'关'+(progress.completed.includes(i)?'，已通关':''));b.setAttribute('aria-current',i===level?'step':'false');b.onclick=()=>select(i);$('levels').appendChild(b);});}
function select(i){game?.destroy?.();level=Math.max(0,Math.min(Number.isFinite(i)?Math.floor(i):0,def.levels.length-1));ended=false;won=false;paused=false;acc=0;last=0;$('overlay').hidden=true;progress.current=level;save();game=def.create({width:W,height:H,level,onComplete:r=>outcome(true,r),onFail:r=>outcome(false,r),sound,seed:20261008+level});$('levelname').textContent=(level+1)+' / '+def.levels.length;$('operation').textContent=def.operation||entry.rule;canvas.setAttribute('aria-label',entry.title+'，'+(def.operation||entry.rule));paintLevels();updateControls();render();}
function undo(){if(won||!game?.canUndo?.())return;const result=game.undo();if(result===false)return;ended=false;won=false;$('overlay').hidden=true;acc=0;render();updateControls();}
function render(){if(!game)return;ctx.save();ctx.clearRect(0,0,W,H);game.render(ctx);ctx.restore();}
function input(type,x,y){if(!ended&&!paused&&type==='down'){game.input('down',{x,y});updateControls();}}
function tick(t){const elapsed=last?Math.min((t-last)/1000,.06):0;last=t;if(!paused&&!ended){acc+=elapsed;while(acc>=1/60){game.update(1/60);acc-=1/60;frame++;if(ended)break;}}render();updateControls();requestAnimationFrame(tick);}
canvas.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;e.preventDefault();unlock();const r=canvas.getBoundingClientRect();input('down',(e.clientX-r.left)*W/r.width,(e.clientY-r.top)*H/r.height);});
$('restart').onclick=()=>select(level);$('again').onclick=()=>select(level);$('undo').onclick=undo;$('recover').onclick=undo;$('next').onclick=()=>{if(level+1<def.levels.length)select(level+1);else location.href='./';};$('sound').hidden=false;$('sound').textContent=saved.muted?'声音关':'声音开';$('sound').onclick=()=>{saved.muted=!saved.muted;$('sound').textContent=saved.muted?'声音关':'声音开';save();if(!saved.muted)unlock();};
window.addEventListener('blur',()=>{paused=true;});window.addEventListener('focus',()=>{paused=false;last=0;});document.addEventListener('visibilitychange',()=>{paused=document.hidden;last=0;});
const dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);$('title').textContent=entry.title;$('new-game').hidden=false;
window.lab={state:()=>({id:entry.id,level,ended,won,paused,game:game?.getState(),progress:structuredClone(progress),soundEvents:soundEvents.length}),select:(_,i)=>select(i),input,undo,audio:()=>({muted:!!saved.muted,state:audioCtx?.state||'locked',events:soundEvents.slice()})};
const requested=params.has('level')?Number(params.get('level')):progress.current;select(requested);if(params.has('level')){params.delete('level');history.replaceState(null,'','play.html?'+params);}requestAnimationFrame(tick);
}
})();
